### ISSUE TITLE
Question about RNA models

### ISSUE THREAD

**Issue by jts** [nanoporetech/kmer_models#5]
Hi,

I'm working on adding support for direct RNA sequencing to nanopolish. My understanding is that the direct RNA protocol sequences 3'->5' but albacore outputs the final read in the 5'->3' orientation. For the RNA models that are provided in this repository, do the levels correspond to the k-mer in the sequencing (3'->5') or basecalled (5'->3') direction?

jared

**Comment by fbrennen** [comment]
Hi @jts -- only the output fastqs are flipped, so that they conform with the direction most bioinformatics tools expect them to be. Everything else (including the basecalling events) is representative of the normal way the strand moves through the pore and should be consistent with that. So the model levels here will correspond to kmers in sequencing (3' -> 5') order.
