### ISSUE TITLE
Normalisation / scaling

### ISSUE THREAD

**Issue by a-slide** [nanoporetech/kmer_models#7]
Hi,
How did you normalise your data to obtain the level_mean for each kmer ? I suspect that it is based on albacore normalisation, so my question might actually be how Albacore is scaling the raw data ?  
Is there any simple way to normalise the raw signal from fast5 files to get values matching those in the kmer model files (ie. scale and shift parameter) ?
Thanks
Adrien

**Comment by cjw85** [comment]
Hi Adrien,

You may wish to look at @jts's nanopolish code to see how it scales these model values to the data (essentially a method of moments approach). Of course in that instance the problem is simplified by having a known sequence of kmers; when the base sequence is not known the same method can be applied iteratively by first estimating the sequence using a HMM. The Oxford Nanopore Technologies' HMM callers used a slightly more sophisticated EM procedure.

**Comment by a-slide** [comment]
Hi Chris,

I had a look at nanopolish already, I was just expecting that you had a more straightforward way to do it. For instance, I suppose Albacore computes the scale and shift internally for each reads. Is there any way to get these values ?

Are the mean values given by albacore similar to the level_mean in the kmer model files ?

Thanks

**Comment by cjw85** [comment]
The older event-based HMM callers did record their resultant scaling parameters to the output files. The raw data RNN callers don't obviously have a view on the data which corresponds to the emissions parameters listed here.

A naive approach to scaling might simply be to calculate the median and median-absolute deviation of a read and either a) the entire set of level_means or b) the set of level_means corresponding to a sequence to which a read is believed to derive. Something similar is done in the scrappie RNN caller to put all reads in a common frame of reference before input into the RNN.

**Comment by cjw85** [comment]
Not in general, again the values given for level_mean are contigent on the data that was used in their training. Due to variation between pores etc. there's no reason to expect the values for other data to be similar: at least a non-zero shift is required (maybe a non-unit scale).

The above is only really true for the deprecate HMM callers; the situation is further complicated by the fact that the "events" output by the RNN callers are simply fixed length blocks of raw data points, not a piece-wise constant modelling of the data.

**Comment by a-slide** [comment]
All right. That was very clear.
Thanks for taking time to answer.
